# Site settings
locale : "en-US"
title : "ReeCocho"
author : "Connor Bramham"
email : "ReeCocho@gmail.com"
description : "My personal portfolio website."
baseurl : ""
url: "http://reecocho.github.io"

# Social links
twitter_username : ReeCochoB
github_username :  ReeCocho
youtube_username : ReeCocho

# Theme settings
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"
  
theme : minima